language: go
go:
- 1.9
install:
- go get -t -v ./...
- go get -v github.com/mitchellh/gox
script:
- chmod +x ./build.sh
- make build
deploy:
  provider: releases
  api_key:
    secure: xs
  file: bin/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: zcong1993/telbot
