language: go
go:
- 1.9
install:
- go get -t -v ./...
- go get -v github.com/mitchellh/gox
script:
- chmod +x ./build.sh
- make build
deploy:
  provider: releases
  api_key:
    secure: D/0GuT54Xm9kGJ+p1ve4GaEAtffWBNq4C629X2rqF/SKcsM7MRXCW6Xsgx0E+NfkWurTAB0YTDigD1pMtAuPPv1g+MadSnpgRpnMgZi/IDrIw3OXyrKKORTzaMOKS0pOZVyX6SnPZphJ0d68peJ4JXCHcECSLzX++rDT53561w6cdmfD2775PHLzNQubhreqakr9BDyJAMgKVj4HgAMEDmtNKvbLHySr9xx4YPdh2pvbWdW/uAh5UAhLWRDx/rwKNCLyzyWSTSzeYodBaqWSH/ljZT+ZIjEuaj2uOPX9ECk8qH3MQEDkyBFHWC9B5NpKi75iA5DWlc3OwiN6OiDkeJkQPm9v1Z5NiCCFjbZ98aRbn2urMBCLvrgUEwwCzpNYRSJF4MfUlA6hncgi7ua51iH1y41hEXxqleoHN6SbjlDlkgdWeQY1AI+eB/p+k53pKv4hopEqaiFI3GkASERIuZ8hYW5uqeu7Y7tivglHJpJdxgfUNGgU/HpMQf0IatsJEYxXmjbnhSKy0jP3JCJUlv0TrZ6WltPt4Z972Op2wtHwBJWTjvLL0HIwhExuNOoWyWRQLVem3wC7KSUwBlLGKACFD1RFC149RNA/EE83mCHTC1G99NQD/IdTWNvzpMwyxGtv6hUeDkpuj9sdBncvGSSzUeio4B/mHmSFPqsxYKY=
  file: bin/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: zcong1993/telbot
